import torch
import glob

def combine_datasets():
    # 1. Find all files that match the pattern "self_play_data_*.pt"
    # This grabs every file generated by your workers
    data_files = glob.glob("self_play_data_*.pt")

    if not data_files:
        print("No data files found! Check your folder.")
        return

    print(f"Found {len(data_files)} files: {data_files}")

    master_dataset = []

    # 2. Load and merge them
    for filename in data_files:
        print(f"Loading {filename}...")
        try:
            data = torch.load(filename, weights_only=False)
            master_dataset.extend(data)  # Append this list to the master list
            print(f" -> Added {len(data)} samples.")
        except Exception as e:
            print(f"Error loading {filename}: {e}")

    # 3. Save the Master File
    output_filename = "MASTER_DATASET.pt"
    torch.save(master_dataset, output_filename)

    print("=" * 40)
    print(f"DONE! Combined {len(master_dataset)} total samples.")
    print(f"Saved to: {output_filename}")
    print("=" * 40)


if __name__ == "__main__":
    combine_datasets()